In [1]:
def test():
    print('Test()for function')
    return
test()

Test()for function


In [2]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
obj=demo()
obj.test()

test()for the class and method


In [1]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)

120

In [2]:
class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("p1=",p1)
        print("p2=",p2)
        
c1=demo2()
c1.accept(10,20)
c1.display

<bound method demo2.display of <__main__.demo2 object at 0x03F07D90>>

In [8]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))
    

300


In [22]:
class person():
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
#derived class
class employee(person):
    def isemployee(self):
        return True
emp=person("sai")
print(emp.getname(),emp.isemployee())
emp1=employee("sunder")
print(emp1.getname(),emp1.isemployee())


sai False
sunder True


In [27]:
import numpy as np
list=[1,2,3,4]
array=np.array(lst)
print(array)


[1 2 3 4]


In [28]:
import numpy as np
int=[1,2,3,4]
array=np.array(lst)
print(array.shape)


(4,)


In [33]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

(2, 3)
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))


[[1 2 3 4 5 6]]


In [41]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))


[[1 2 3]
 [4 5 6]]


In [43]:
a1=np.random.normal([(5,0,5,10)])
print(a1)

[[ 4.9960817  -0.20970939  5.72543743  9.26397499]]


In [45]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [47]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [49]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [50]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [51]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [52]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [54]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [57]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row: ",a1[0])

first row:  [1 2 3]


In [56]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row: ",a1[1][1])

second row:  5


In [58]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [59]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicingrow coloum :",a1[:,1])

slicingrow coloum : [2 5]


In [60]:
a1=np.random.normal(5,1,10)
print(a1)

[6.36632001 6.90957775 3.9738174  6.36865911 5.82070691 5.64801023
 5.80239771 5.16263412 5.62103077 3.10774949]


In [61]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.09355254 5.62043361 4.66196347 5.39536177 5.7237682  4.25467952
 3.45603361 4.98859189 4.18505776 2.33900307]
min value= 2.3390030650923483
max value= 5.723768202400693
mean value= 4.571844544593876
median value= 4.825277682964523


In [62]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [63]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [73]:
import numpy as np
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print(c[2])

21


In [1]:
import pandas as pd
dict1={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "Emailid":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","karnth@gmail.com"],"Mobilenumber":["888","777","999","555","666","444"],"Addres":["hyd","hyd","hyd","hyd","hyd","hyd"]}
     
b=pd.DataFrame(dict1)
print(b)

     Name           Emailid Mobilenumber Addres
0    Anil    anil@gmail.com          888    hyd
1   Akhil   akhil@gmail.com          777    hyd
2  Dinesh  dinesh@gmail.com          999    hyd
3  Harsha  harsha@gmail.com          555    hyd
4    Ajay    ajay@gmail.com          666    hyd
5  Kranth  karnth@gmail.com          444    hyd
